### PR TITLE
Upgrade google.golang.org/api

### PR DESCRIPTION
**Pull request by nunosilva800**

### CODE REVIEW

**Comment by nunosilva800** [comment]
`go test ./...` fails with lots of errors:

```
2021/08/12 16:38:34 created 0 files
2021/08/12 16:38:34 created 100 files
2021/08/12 16:38:34 created 200 files
2021/08/12 16:38:34 created 300 files
2021/08/12 16:38:34 created 400 files
2021/08/12 16:38:34 created 500 files
2021/08/12 16:38:34 created 600 files
2021/08/12 16:38:34 created 700 files
2021/08/12 16:38:34 created 800 files
2021/08/12 16:38:34 created 900 files
2021/08/12 16:38:34 created 1000 files
--- FAIL: TestOSFS (0.17s)
    straw_logging_streamstore_test.go:76: 
        
        before CreateWriteOnly : 
        [
          "/var/folders/bv/12lnmj7j2hd4xvknyh7439wr0000gp/T/straw_test_452413408/TestCreateNewWriteOnly"
        ]
        {}
    straw_logging_streamstore_test.go:76: 
        
        after CreateWriteOnly : 
        [
          "/var/folders/bv/12lnmj7j2hd4xvknyh7439wr0000gp/T/straw_test_452413408/TestCreateNewWriteOnly"
        ]
        {}
.......
   straw_logging_streamstore_test.go:76: 
        
        after Stat : 
        [
          "/var/folders/bv/12lnmj7j2hd4xvknyh7439wr0000gp/T/straw_sftp_test020012479/TestStat/dir/file"
        ]
        {}
    straw_logging_streamstore_test.go:76: 
        
        before Stat : 
        [
          "/"
        ]
        {}
    straw_logging_streamstore_test.go:76: 
        
        after Stat : 
        [
          "/"
        ]
        {}
    --- FAIL: TestSFTPFS/sftpfs_TestStat (0.00s)
        straw_test.go:387: 
                Error Trace:    straw_test.go:387
                Error:          Not equal: 
                                expected: 4096
                                actual  : 96
                Test:           TestSFTPFS/sftpfs_TestStat
FAIL
FAIL    github.com/uw-labs/straw        4.861s
?       github.com/uw-labs/straw/gcs    [no test files]
?       github.com/uw-labs/straw/s3     [no test files]
?       github.com/uw-labs/straw/sftp   [no test files]
```

**Review by SpeedyCoder — APPROVED** [review]

**Comment by SpeedyCoder** [comment]
Was it failing before you updated the dependencies or was it caused by the update?

**Comment by mjgarton** [comment]
It's failing here https://github.com/uw-labs/straw/blob/master/straw_test.go#L387

I think it's a problem with the test.  It expects `4096` as the "size" of the directory entry, but is getting `96`.  I'm going to bet you are running on macos and I never thought about what the dir size would be on macos.

**Review by mjgarton — APPROVED** [review]

**Comment by nunosilva800** [comment]
> Was it failing before you updated the dependencies or was it caused by the update?

Yes, also failed.



> I'm going to bet you are running on macos and I never thought about what the dir size would be on macos.

And you win the bet!

**Comment by nunosilva800** [comment]
btw, that seems to be just the tip of the iceberg. there are tons of other test errors on macos past that one.

**Pull request closed without merging**
